### ISSUE TITLE
Javadoc 404  以及个人疑问

### ISSUE THREAD

**Issue by SmileYik** [Saukiya/SX-Attribute#4]
SX-Attribute 开发 - 注册条件
开发总览   JavaDoc   注册属性   注册条件   API
================================
JavaDoc,API页面404,希望修复

个人疑问:
能否实现制造个插件插件通过API增加属性,并且当反复添加的时候人物总属性不会总是增加或者外部添加的属性被洗掉.
因为我的描述可能不是很清楚,你可以通过这个例子了解我的想法:

1. 假如一位玩家的某个属性没有修改时为 75. 
2. 一个插件利用API对属性修改, 添加了30属性值后.总属性值变为105
3. 后来这个插件将原来修改的的30属性值变为25后添加到玩家原有的属性值(75)上,总属性值变为100

在第2步过程中 修改属性后(只通过api对属性修改一次), 修改的属性是否会被玩家的装备修改或其他行动重新洗回75
在第3步过程中 玩家原有的属性值是第二步修改过后的原有属性值(105)还是原本玩家的属性值(75)

感谢作者浏览到最后,并希望能够解开我的疑问.

**Comment by Saukiya** [comment]
这个嘛，sx群文件里面有javadoc 2.0的，打算在github重开一个项目来维护3.0

**Comment by Saukiya** [comment]
另外API内是可以按照你的方法修改属性值的，不过2.0修改属性值需要用一个List<String>来读取SXAttributeData

**Comment by SmileYik** [comment]
感谢作者回复

**Comment by Saukiya** [comment]
这个项目已经恢复到2.0版本了，javadoc也在里面（可惜我在本地查看才是优化了，在这边没法弄Player、String的javadoc超链接），3.0我另开一个项目

**Comment by SmileYik** [comment]
谢谢, 另外我还有个问题,
我尝试过用getAPIStats获取玩家的数据信息然后add另外一个数据信息
用setEntityAPIData(玩家,另外一个数据信息)
getEntityAllData获取玩家属性信息后add另外一个数据信息
玩家的属性都没有发生改变,是我的操作有问题吗?
(同时还试了下UpdateEventData事件...貌似都没有触发这个事件)

**Comment by SmileYik** [comment]
我实验了下,我添加的另外一个数据信息应该是有效的
[09:27:40 WARN]: b
[09:27:49 INFO]: Damage#20.0/30.0/0.0/0.0/0.0/0.0//Ignition#14.0//Slowness#4.44
[09:27:49 INFO]: Damage#20.0/30.0/0.0/0.0/0.0/0.0//Ignition#14.0//Slowness#4.44
[09:27:49 INFO]: Damage#20.0/30.0/0.0/0.0/0.0/0.0//Ignition#14.0//Slowness#4.44//Lightning#20.0//Health#200.0//Speed#50.0

**Comment by Saukiya** [comment]
有个检查为isVaild 这个会检测数据是否有效（也是由sx内loadListData实现的，算是2.0对外接口的弊端）
你可以clone sx源码，在SXAtteibuteData下的vaild上加个`@Getter`，lib文件夹在项目内

**Comment by SmileYik** [comment]
emm,我还是比较疑惑为什么我添加的数据依旧无效
`
		SXAttributeData data = new SXAttributeData();
		
		for(ItemStack item:pd.getItems().values()){
			data = data.add(FashionCloth.sxaApi.getItemData(null, null, item));
		}
		FashionCloth.sxaApi.setEntityAPIData(FashionCloth.class, p.getUniqueId(), data);
`

这是我更新属性的代码,请您看看是否有问题

**Comment by Saukiya** [comment]
你试下这段吧
`FashionCloth.sxaApi.setEntityAPIData(FashionCloth.class, p.getUniqueId(), FashionCloth.sxaApi.getItemData(null, null, pd.getItems().values()));`
