### ISSUE TITLE
MCBBS挂了，没地方下载了。

### ISSUE THREAD

**Issue by qq307198081** [Saukiya/SX-Attribute#9]
麻烦更新一下下载地址。

**Comment by LittleSwift** [comment]
最新版尝试编译但貌似因为jdk没有自带nashorn无法通过，如果可能麻烦Contributor告诉我一下你们所使用的jdk
这里是我自行编译的 cc2f02f 版本的插件，不支持最新的特性

https://yuyanmc.lanzoub.com/i2zA51rmmlaj
密码:7bqv

此外，3.x和2.x版本可以在其他branch中找到

**Comment by Saukiya** [comment]
https://github.com/Saukiya/SX-Attribute/releases/tag/3.5.0
